### ISSUE TITLE
Replace `tabulario/iceberg-rest` with `apache/iceberg-rest-fixture`

### ISSUE THREAD

**Issue by Fokko** [apache/iceberg-go#221]
### Feature Request / Improvement

We now publish the `apache/iceberg-rest-fixture` from the Java repository. The `tabulario` is severely outdated.

**Comment by hendoxc** [comment]
Hey can I take this?

**Comment by Fokko** [comment]
@hendoxc Sure, go for it!

**Comment by hendoxc** [comment]
https://github.com/apache/iceberg-go/pull/222
