### ISSUE TITLE
Is there a roadmap?

### ISSUE THREAD

**Issue by lovromazgon** [apache/iceberg-go#24]
### Question

I've noticed that this project is still in its early stages, and I'm trying to determine when it will reach a point where we can begin experimenting with it. Is there a project timeline or roadmap available? It would already be helpful if you could provide a checklist of (un)implemented features and a comparison to the Java implementation, similar to what the [Python implementation](https://py.iceberg.apache.org/feature-support/) provides, and tick the boxes once a feature is ready.

**Comment by zeroshade** [comment]
I'll try to add the checklist to the readme in the next day or so to provide more information and a roadmap.

**Comment by lovromazgon** [comment]
Thank you @zeroshade!
