### ISSUE TITLE
GCS support?

### ISSUE THREAD

**Issue by thorfour** [apache/iceberg-go#60]
Was looking into this library and saw that GCS support was in the matrix but was unsupported yet.

Looking at the io package that abstracts the storage layer and I was wondering if this could be implemented by https://github.com/thanos-io/objstore/ ?

If so it already supports S3, GCS as well as local filesystem and much more.

**Comment by zeroshade** [comment]
That's definitely an interesting and valid idea. Would you be willing to sketch out a PR for it?

**Comment by thorfour** [comment]
Yea absolutely!

**Comment by thorfour** [comment]
@zeroshade I took a stab at what it might look like in #66 let me know what you think.
